#!/usr/bin/env node

import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { format } from "prettier";
import { isDirectExecution } from "../src/direct-execution.js";
import { canonicalizeJson, sha256Hex } from "../src/release-assets.js";

const defaultPackageRoot = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "..",
);

export interface GenerateReleaseDataOptions {
  packageRoot?: string;
  outputPath?: string;
  check?: boolean;
}

export interface GenerateReleaseDataResult {
  packageVersion: string;
  rulesSha256: string;
  canonicalRulesJson: string;
  generatedSource: string;
}

function chunk(value: string, width = 96): string[] {
  const chunks: string[] = [];
  for (let offset = 0; offset < value.length; offset += width) {
    chunks.push(value.slice(offset, offset + width));
  }
  return chunks;
}

export async function generateReleaseData(
  options: GenerateReleaseDataOptions = {},
): Promise<GenerateReleaseDataResult> {
  const packageRoot = resolve(options.packageRoot ?? defaultPackageRoot);
  const packagePath = join(packageRoot, "package.json");
  const rulesPath = join(packageRoot, "rules", "default-patterns.json");
  const outputPath = resolve(
    options.outputPath ??
      join(packageRoot, "src", "generated", "release-data.ts"),
  );
  const packageJson: unknown = JSON.parse(readFileSync(packagePath, "utf8"));
  if (
    !packageJson ||
    typeof packageJson !== "object" ||
    typeof (packageJson as { version?: unknown }).version !== "string"
  ) {
    throw new TypeError("package.json must contain a string version");
  }
  const packageVersion = (packageJson as { version: string }).version;
  const rules: unknown = JSON.parse(readFileSync(rulesPath, "utf8"));
  const canonicalRulesJson = canonicalizeJson(rules);
  const rulesSha256 = sha256Hex(canonicalRulesJson);
  const encodedChunks = chunk(
    Buffer.from(canonicalRulesJson, "utf8").toString("base64"),
  );
  const generatedSource = await format(
    `// Generated by scripts/generate-release-data.ts. Do not edit.\n` +
      `export const PACKAGE_VERSION = ${JSON.stringify(packageVersion)};\n` +
      `export const EMBEDDED_RULES_SHA256 = ${JSON.stringify(rulesSha256)};\n` +
      `export const EMBEDDED_DEFAULT_PATTERNS_BASE64 = [${encodedChunks
        .map((entry) => JSON.stringify(entry))
        .join(",")}].join("");\n`,
    { parser: "typescript" },
  );

  if (options.check) {
    let current = "";
    try {
      current = readFileSync(outputPath, "utf8");
    } catch {
      // The mismatch below provides the actionable error.
    }
    if (current !== generatedSource) {
      throw new Error(
        "Generated release data is stale; run npm run generate:release-data",
      );
    }
  } else {
    writeFileSync(outputPath, generatedSource);
  }

  return {
    packageVersion,
    rulesSha256,
    canonicalRulesJson,
    generatedSource,
  };
}

if (isDirectExecution(import.meta.url, process.argv[1])) {
  await generateReleaseData({ check: process.argv.includes("--check") });
}
